name: pipe_crd
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - dask==2025.3.0
  - distributed==2025.3.0
  - dask-jobqueue==0.9.0
  - pandas
  - cdshealpix==0.7.2
  - nested-pandas==0.6.6
  - numpy
  - pyyaml
  - lsdb=0.7.3
  - hats=0.7.3
  - hats-import=0.7.3
  - tables-io
  - h5py

