name: pipe_crd
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - dask
  - distributed
  - dask-jobqueue         
  - pandas
  - numpy
  - pyyaml
  - lsdb=0.7.3
  - hats=0.7.3
  - hats-import=0.7.3
  - tables-io                  
  - h5py

